### ISSUE TITLE
Create Learning Model

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/rolf-one#1]
**User Story:** 

As a learner I want a flexible educational model. I want to choose the subject matter and have the app generate a pleasing learning model that walks me through the learning process at my own pace.

**Acceptance Criteria:**

- [ ] The submit button on the input form produces a success page and sends a message to the learner when the learning model is ready.
- [ ] The learning model prompts the learner to answer questions to progress through the module.
- [ ] The learner is directed through the process at their own pace based on the accuracy of their answers. Pausing to repeat sections where they are less accurate.

**Tasks:**

- [ ] Build an AI model that will convert the input media into data.
- [ ] Build an AI learning model that will process the data from inputs into an interactive educator on the chosen topic. 
- [ ] Make the learning model react with logic to learner responses. The responses to the learning model's questions determine the pace they progress through the process, drilling down into content where necessary.
- [ ] Style the learning model in an appealing way using the same colour palette used on the home page.
