### ISSUE TITLE
Create Input Model

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/rolf-one#2]
**User Story:** 

As a learner I want a flexible input model. I want to choose the subject matter, easily input it and have the app generate a pleasing learning model that walks me through the learning process at my own pace.

**Acceptance Criteria:**

- [ ] Learners can navigate to the input form from a button below the header/nav bar or from the features section.
- [ ] The input form allows learners to enter their learning goals, a message, select the specific category they are interested in, the type of media they want to input and the date range for the learning goal.
- [ ] The submit button produces a success page and sends a message to the learner when the input model is ready.

**Tasks:**

- [ ] Create a start now button in the header linking to the input form.
- [ ] Add start now buttons to the feature page linking to the input form.
- [ ] Create a responsive input form using Bootstrap that allows visitors to select the type of media to input, the topic category, their contact details, a message, date range for their learning goal as well as a submit button.
- [ ] Style the input form using the same colour palette and fonts seen on the home page.
- [ ] Ensure that submitting the form triggers a success page for the visitor.
- [ ] Build an AI model that will convert the input media into data.
